services:
    mqtt:
        image: eclipse-mosquitto:2
        ports:
            - "1883:1883"
        volumes:
            - ./config/mosquitto:/mosquitto/config/:ro
        restart: unless-stopped

    db-init:
        image: keinos/sqlite3:3.51.1
        volumes:
            - ./config:/config:ro
            - ./data:/data
        command: >
            sh -c 'sqlite3 /data/vitens.db < /config/tables.sql'
        restart: "no"

    modeltrainer:
        build: ./modeltrainer
        volumes:
            - ./traindata:/traindata:ro
            - ./data:/data
        restart: "no"

    dashboard:
        build: ./dashboard
        environment:
            - SQLITE3_PATH=/data/vitens.db
            - MQTT_HOST=mqtt
            - MQTT_PORT=1883
        volumes:
            - ./data:/data
            - ./dashboard/static:/app/static
        ports:
            - "5000:5000"
        depends_on:
            mqtt:
                condition: service_started
            db-init:
                condition: service_completed_successfully
        restart: unless-stopped

    inserter:
        build: ./inserter
        environment:
            - SQLITE3_PATH=/data/vitens.db
            - MQTT_HOST=mqtt
            - MQTT_PORT=1883
        volumes:
            - ./data:/data
        depends_on:
            mqtt:
                condition: service_started
            db-init:
                condition: service_completed_successfully
            modeltrainer:
                condition: service_completed_successfully
        restart: unless-stopped

    collector:
        build: ./collector
        environment:
            - SQLITE3_PATH=/data/vitens.db
            - MQTT_HOST=mqtt
            - MQTT_PORT=1883
        volumes:
            - ./data:/data
        depends_on:
            mqtt:
                condition: service_started
            db-init:
                condition: service_completed_successfully
        restart: unless-stopped

    replay:
        build: ./replay
        environment:
            - SQLITE3_PATH=/data/vitens.db
            - MQTT_HOST=mqtt
            - MQTT_PORT=1883
        volumes:
            - ./data:/data
        depends_on:
            mqtt:
                condition: service_started
            db-init:
                condition: service_completed_successfully
        restart: unless-stopped

    sensordaemon:
        build: ./sensordaemon
        environment:
            - MQTT_HOST=mqtt
            - MQTT_PORT=1883
        profiles:
            - debug
        depends_on:
            mqtt:
                condition: service_started
        restart: unless-stopped
