services:
    mqtt:
        image: eclipse-mosquitto:2
        profiles:
            - debug
        env_file: .env
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - ./config/mosquitto:/mosquitto/config/:ro
            - ./data/mosquitto:/mosquitto/data/:rw

        command: >
          sh -lc '
            set -eu;
            : "${MQTT_USER:?MQTT_USER not set}";
            : "${MQTT_PASSWD:?MQTT_PASSWD not set}";
            if [ ! -f /mosquitto/data/passwd ]; then
              touch /mosquitto/data/passwd;
            fi
            if ! grep -qE "^${MQTT_USER}:" /mosquitto/data/passwd; then
              mosquitto_passwd -b /mosquitto/data/passwd "$MQTT_USER" "$MQTT_PASSWD";
            else
              mosquitto_passwd -b /mosquitto/data/passwd "$MQTT_USER" "$MQTT_PASSWD";
            fi
            exec mosquitto -c /mosquitto/config/mosquitto.conf
          '
        restart: unless-stopped

    db-init:
        image: keinos/sqlite3:3.51.1
        profiles:
            - prod
            - debug
        env_file: .env
        volumes:
            - ./config:/config:ro
            - ./data:/data
        command: >
            sh -c 'sqlite3 $DB_PATH < /config/tables.sql'
        restart: "no"

    modeltrainer:
        build: ./modeltrainer
        profiles:
            - prod
            - debug
        env_file: .env
        volumes:
            - ./traindata:/traindata:ro
            - ./data:/data
        restart: "no"

    dashboard:
        build: ./dashboard
        profiles:
            - prod
            - debug
        env_file: .env
        volumes:
            - ./data:/data
            - ./dashboard/static:/app/static
        ports:
            - "5000:5000"
        depends_on:
            mqtt:
                condition: service_started
            db-init:
                condition: service_completed_successfully
        restart: unless-stopped

    inserter:
        build: ./inserter
        profiles:
            - prod
            - debug
        env_file: .env
        volumes:
            - ./data:/data
        depends_on:
            mqtt:
                condition: service_started
            db-init:
                condition: service_completed_successfully
            modeltrainer:
                condition: service_completed_successfully
        restart: unless-stopped

    collector:
        build: ./collector
        profiles:
            - prod
            - debug
        env_file: .env
        volumes:
            - ./data:/data
        depends_on:
            mqtt:
                condition: service_started
            db-init:
                condition: service_completed_successfully
        restart: unless-stopped

    replay:
        build: ./replay
        profiles:
            - prod
            - debug
        env_file: .env
        volumes:
            - ./data:/data
        depends_on:
            mqtt:
                condition: service_started
            db-init:
                condition: service_completed_successfully
        restart: unless-stopped

    sensordaemon:
        build: ./sensordaemon
        profiles:
            - debug
        env_file: .env
        depends_on:
            mqtt:
                condition: service_started
        restart: unless-stopped